=== Skizaru/Compilation2/TP2/contactDTD.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT Personnes (individu+)>
<!ELEMENT individu (nom, prenom, sexe, civilite, email, contacts)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT sexe EMPTY>
<!ELEMENT civilite EMPTY>
<!ELEMENT email (#PCDATA)>
<!ELEMENT contacts (contact+)>
<!ELEMENT contact (#PCDATA)>
<!ATTLIST contact
		type (chat|social|global) #REQUIRED
		name (Skype|Facebook|Linkedin|gmail|Twitter)  #REQUIRED
>
<!ATTLIST sexe
		type (M|F) #REQUIRED
>
<!ATTLIST civilite
		type (M|Mme|Mlle) #REQUIRED
>

=== Skizaru/Compilation2/TP2/contacts.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE Personnes SYSTEM "contactDTD.dtd"> 
<Personnes>
	<individu>
		<nom>Jannot</nom>
		<prenom>Cédric</prenom>
		<sexe type="M"></sexe>
		<civilite type="M"></civilite>
		<email>cedric.jannot@etu.unilim.fr</email>
		<contacts>	
			<contact type="chat" name="Skype">Skizaru</contact>
			<contact type="social" name="Twitter">Touffix</contact>
			<contact type="social" name="Facebook">Cédric Jannot</contact>
			<contact type="global" name="gmail">cedric.skiza@gmail.com</contact>
		</contacts>
	</individu>
	<individu>
		<nom>Bharat</nom>
		<prenom>Romain</prenom>
		<sexe type="M"></sexe>
		<civilite type="M"></civilite>
		<email>romain.bharat@etu.unilim.fr</email>
		<contacts>	
			<contact type="chat" name="Skype">Skizaru</contact>
			<contact type="social" name="Twitter">Touffix</contact>
			<contact type="social" name="Facebook">Cédric Jannot</contact>
			<contact type="global" name="gmail">cedric.skiza@gmail.com</contact>
		</contacts>
	</individu>
	<individu>
		<nom>Lestage</nom>
		<prenom>Marine</prenom>
		<sexe type="F"></sexe>
		<civilite type="Mlle"></civilite>
		<email>marine.lestage@etu.unilim.fr</email>
		<contacts>	
			<contact type="chat" name="Skype">Skizaru</contact>
			<contact type="social" name="Twitter">Touffix</contact>
			<contact type="social" name="Facebook">Cédric Jannot</contact>
			<contact type="global" name="gmail">cedric.skiza@gmail.com</contact>
		</contacts>
	</individu>
</Personnes>
